name: neurocomputing
channels:
  - apple
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy 
  - scikit-learn
  - matplotlib
  - jupyter
  - tensorflow-deps # macos only
  - pip:
    - tensorflow-macos # macos only
    - tensorflow-metal # macos only