project:
  type: book
  output-dir: ../docs

book:
  title: "Neurocomputing"
  author: "Julien Vitay"
  search: true
  sidebar:
    style: docked
    type: light
    background: white
    logo: notes/img/tuc-new.png
  page-footer: "Copyright Julien Vitay - <julien.vitay@informatik.tu-chemnitz.de>" 
  chapters:
    - index.qmd
    - part: "**Introduction**"
      chapters:
      - notes/1.1-Introduction.qmd
      - notes/1.2-Math.qmd
      - notes/1.3-Neurons.qmd
    - part: "**Linear algorithms**"
      chapters:
      - notes/2.1-Optimization.qmd
      - notes/2.2-LinearRegression.qmd
      - notes/2.3-LinearClassification.qmd
      - notes/2.4-LearningTheory.qmd
    - part: "**Neural networks**"
      chapters:
      - notes/3.1-NeuralNetworks.qmd
      - notes/3.2-DNN.qmd
    - part: "**Computer Vision**"
      chapters:
      - notes/4.1-CNN.qmd
      - notes/4.2-ObjectDetection.qmd
      - notes/4.3-SemanticSegmentation.qmd
    - part: "**Generative modeling**"
      chapters:
      - notes/5.1-Autoencoders.qmd
      - notes/5.2-RBM.qmd
      - notes/5.3-GAN.qmd
    - part: "**Recurrent neural networks**"
      chapters:
      - notes/6.1-RNN.qmd
      - notes/6.2-NLP.qmd
    - part: "**Self-supervised learning**"
      chapters:
      - notes/7.1-Transformers.qmd
      - notes/7.2-ContrastiveLearning.qmd
      - notes/7.3-VisionTransformer.qmd
      - notes/7.4-DiffusionModels.qmd
    - part: "**Outlook**"
      chapters:
      - notes/8.1-Limits.qmd
      - notes/8.2-Beyond.qmd
    - part: "**Exercises**"
      chapters:
      - exercises/Content.qmd
      - exercises/Installation.qmd
      - exercises/1-Python.ipynb
      - exercises/2-Numpy-solution.ipynb
      - exercises/3-LinearRegression-solution.ipynb
      - exercises/4-MLR-solution.ipynb
      - exercises/5-Crossvalidation-solution.ipynb
      - exercises/6-LinearClassification-solution.ipynb
      - exercises/7-SoftmaxClassifier-solution.ipynb
      - exercises/8-MLP-solution.ipynb
      - exercises/9-MNIST-solution.ipynb
      - exercises/10-CNN-solution.ipynb
      - exercises/11-TransferLearning-solution.ipynb
      - exercises/12-VAE-solution.ipynb
      - exercises/13-RNN-solution.ipynb
    - references.qmd


bibliography: DeepLearning.bib
csl: frontiers.csl

format:
  html:
    theme: [sandstone, custom.scss]
    page-layout: full
    number-depth: 2
    number-sections: false
    toc: true
    smooth-scroll: true
    html-math-method: katex
    #fig-cap-location: margin
    #reference-location: margin

filters:
  - center_images.lua
  - quarto

